//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FatCloud.Client.FatDB;
using FatDB_SQL_Sample;
using System;



[System.SerializableAttribute()]
[FatCloud.Client.FatDB.FatDBContextAttribute(Version=0)]
public class product : IProduct
{
    [NonSerialized]
    private FatDBClientVersionInfo _versionInfo = new FatDBClientVersionInfo(-1, DateTime.UtcNow);

    [FatCloud.Client.FatDB.FatDBKeyAttribute()]
    [FatCloud.Client.FatDB.FatDBLocalityKeyAttribute()]
    [FatCloud.Client.FatDB.FatDBIndexedAttribute()]
    public int ProductKey { get; set; }

    public string ProductName { get; set; }
    
    public decimal Cost { get; set; }

    public string Color { get; set; }
    
    public string ModelName { get; set; }
 
    public string Description { get; set; }   
   
    public product() {}

    // copy constructor
    public product(product x, bool copyVersion)
    {
        if (copyVersion == true)
        {
            _versionInfo = x._versionInfo;
        }
        else
        {
            _versionInfo = null;
        }

        ProductKey  = x.ProductKey;
        ProductName = x.ProductName;
        Color       = x.Color;
        Cost        = x.Cost;
        Description = x.Description;
        ModelName   = x.ModelName;
    }

    public product(Product x)
    {
        _versionInfo = null;
        ProductKey   = x.ProductKey;
        ProductName  = x.ProductName;
        Color        = x.Color;
        Cost         = x.Cost;
        Description  = x.Description;
        ModelName    = x.ModelName;        
    }

    public product(FatDBClientRecord x)
    {
        _versionInfo = x.VersionInfo;
        ProductKey   = ((product)x.Value).ProductKey;
        ProductName  = ((product)x.Value).ProductName;
        Color        = ((product)x.Value).Color;
        Cost         = ((product)x.Value).Cost;
        Description  = ((product)x.Value).Description;
        ModelName    = ((product)x.Value).ModelName;
    }

    public FatDBClientVersionInfo GetVersionInfo()
    {
        return _versionInfo;
    }
}
