//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FatCloud.Client.FatDB;
using FatCloud.Client.FatDBMS.Model;
using FatDB_SQL_Sample;
using System;



[System.SerializableAttribute()]
[FatCloud.Client.FatDB.FatDBContextAttribute(Version=0)]
[FatCloud.Client.FatDB.FatDBSqlTableAttribute("product")]
public class product_cache : IProduct
{    
    [NonSerialized]
    private FatDBClientVersionInfo _versionInfo = new FatDBClientVersionInfo(-1, DateTime.UtcNow);

    [FatCloud.Client.FatDB.FatDBKeyAttribute()]
    [FatCloud.Client.FatDB.FatDBLocalityKeyAttribute()]
    public int ProductKey { get; set; }

    public string ProductName { get; set; }
    
    public decimal Cost { get; set; }

    public string Color { get; set; }
     
    public string ModelName { get; set; }
    
    public string Description { get; set; }
   
    // copy constructor
    public product_cache(product_cache x)
    {
        _versionInfo = x._versionInfo;
        ProductKey   = x.ProductKey;
        ProductName  = x.ProductName;
        Color        = x.Color;
        Cost         = x.Cost;
        Description  = x.Description;
        ModelName    = x.ModelName;
    }

    public product_cache() {}

    // copy constructor
    public product_cache(Record x)
    {
        _versionInfo = new FatDBClientVersionInfo(x.Version.Version, x.Version.LastChanged);
        ProductKey   = (int)x.KeyValuePairs["ProductKey"];
        ProductName  = (string)x.KeyValuePairs["ProductName"];
        Color        = (string)x.KeyValuePairs["Color"];
        Cost         = (decimal)x.KeyValuePairs["Cost"];
        Description  = (string)x.KeyValuePairs["Description"];
        ModelName    = (string)x.KeyValuePairs["ModelName"];
    }

    public FatDBClientVersionInfo GetVersionInfo()
    {
        return _versionInfo;
    }
}
